CREATE DATABASE CADASTROALUNOS
GO

USE CADASTROALUNOS
GO

CREATE TABLE ALUNOS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL, 
	TELEFONE VARCHAR(30) NOT NULL,
	IMAGEM VARBINARY(MAX) NULL,
);
GO
